change deploy logic
microservices-course-itmo/deployment-service pull request #18
Opened 2020-11-08 15:54 UTC by ilyashn

2020-11-08 16:14 UTC, Arthasasyan requested changes

2020-11-08 16:14 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/vo/ApplicationDeployRequestWrapper.java
> +    private String version;
`final`

2020-11-08 16:14 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
> +                        ?: "unknown", "LocalDateTime.now()", "test user", ApplicationInstanceStatus.STARTING, "test url")
Поменяй тип данных на `LocalDateTime` тогда уж

2020-11-08 16:14 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
> +                                .withImage("${applicationTemplateVO.name}:dev_${version}")
У ContainerSpec разве нет метода `withVersion`?

2020-11-08 16:14 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
> +                        ?: "unknown", "LocalDateTime.now()", "test user", ApplicationInstanceStatus.STARTING, "test url")
Давай сменим тогда заглушку для пользователя на, например, `system`

2020-11-08 16:14 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/vo/ApplicationDeployRequest.java
> +    private String name;
`final`

2020-11-08 16:14 UTC, Arthasasyan commented
@kovinz посмотри пожалуйста
@ilyashn Еще выставляй в `applicationInstance` переданную версию

2020-11-08 18:46 UTC, ilyashn commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
> +                                .withImage("${applicationTemplateVO.name}:dev_${version}")
такого метода нет 
я не нашел другой возможности указать версию

2020-11-08 19:02 UTC, Arthasasyan requested changes

2020-11-08 19:02 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
> +                    .dateCreated(it.dateCreated.toString())
В принципе, можно поменять тип в VO на LocalDateTime -- он вполне спокойно сам преобразуется в строку

2020-11-08 19:02 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
>                      .alias("STUB")
Давай добавим alias к запросу на деплой и будем здесь прописывать?

2020-11-08 19:02 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
>                      .containerId("STUB")
Поля больше нет, удалить

2020-11-09 06:37 UTC, Arthasasyan approved these changes

2020-11-09 06:38 UTC, merged