Add RunServiceCommandProvider
microservices-course-itmo/deployment-service pull request #3
Opened 2020-10-14 16:15 UTC by lolwhatvvw

2020-10-14 16:18 UTC, Arthasasyan requested changes
Где эндпоинты в контроллере

2020-10-14 17:39 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/command/provider/impl/RunServiceCommandProvider.java
> +    public static final String COMMAND = "docker service ls";
почему переменная public? и по кодстайлу статик переменные идут выше обычных

2020-10-14 17:40 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/command/provider/impl/RunServiceCommandProvider.java
> +        this.commandProcessor = commandProcessor;
можно поставить аннотацию requiredArgsConstructor на компонент и не юзать сеттер с аннотацией Autowired - код станет чище

2020-10-14 17:40 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/command/provider/impl/RunServiceCommandProvider.java
> +        final Map<String, Object> payload = new HashMap<>();
слово final юзать внутри методов не обязательно - лучше убрать

2020-11-03 18:33 UTC, Arthasasyan commented
Требования изменились

2020-11-03 18:33 UTC, closed without merging