Start stop dev
microservices-course-itmo/deployment-service pull request #42
Opened 2021-03-14 13:16 UTC by ilyashn

2021-03-14 18:49 UTC, Arthasasyan requested changes

2021-03-14 18:49 UTC, Arthasasyan commented on README.md
> +### Instruction to run this app locally:
Инструкция в dev не нужна, по ней локально не развернешься

2021-03-14 18:49 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/controller/DeploymentController.java
> +        applicationInstanceManager.restartApplication(this.deploymentService.getSingleInstanceById(id));
Лучше, чтобы он получал id, а потом внутри сам запрашивал инстанс

2021-03-14 18:49 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceManagerImpl.java
> +        if (dockerService.getVersion() != null) {
Чет не очень понял, как это работает

2021-03-14 19:57 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/controller/DeploymentController.java
> +@CrossOrigin
Это вроде для для локального запуска добавляли, разве нет?

2021-03-14 19:57 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/controller/DeploymentController.java
> +public class    DeploymentController {
Очень важное изменение) Я думаю лишние пробелы можно удалить

2021-03-14 19:59 UTC, kovinz commented on src/main/java/com/wine/to/up/deployment/service/controller/DeploymentController.java
> +        applicationInstanceManager.restartApplication(this.deploymentService.getSingleInstanceById(id));
Если нам при каждом вызове сервиса нужно выполнять одно и то же действие в параметре - его явно лучше убрать внутрь

2021-03-16 16:49 UTC, Arthasasyan requested changes

2021-03-16 16:49 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/controller/DeploymentController.java
> +            return ResponseEntity.ok(deploymentService.stopApplication(id));
Предполагается, что статус должен сам выставляться из эксепшена
То есть, что подобная конструкция есть в спринге уже

2021-03-16 18:45 UTC, Arthasasyan approved these changes

2021-03-16 18:45 UTC, merged