add stopTraffic
microservices-course-itmo/deployment-service pull request #48
Opened 2021-03-28 10:03 UTC by DuckDivision

2021-03-28 13:06 UTC, Arthasasyan requested changes

2021-03-28 13:06 UTC, Arthasasyan commented on src/main/kotlin/com/wine/to/up/deployment/service/service/impl/ApplicationInstanceServiceImpl.kt
>          if (attributes != null && attributes.isTestInstance) {
Проверка на null не нужна, она уже была выше

2021-03-30 12:47 UTC, Arthasasyan requested changes

2021-03-30 12:47 UTC, Arthasasyan commented on src/main/java/com/wine/to/up/deployment/service/vo/Attributes.java
> +    public Boolean isTestInstance() {
Возвращает то он boolean, тут null быть не может в ответе

2021-03-30 13:06 UTC, Arthasasyan approved these changes

2021-03-30 13:49 UTC, kovinz approved these changes

2021-03-30 14:23 UTC, ilyashn approved these changes

2021-03-30 15:06 UTC, merged